[auth]
cookie_name = "goshala_dashboard_cookie"
signature_key = "some_random_secret_key"
cookie_expiry_days = 1

[auth.credentials]
names = ["Admin", "Viewer"]
usernames = ["admin", "viewer"]
passwords = [
  "$2b$12$I251HoVZV7Io507uBhLpl.jm6NTqEn802tz7J6yQ7YpEjgh.YfIse",
  "$2b$12$bVq7lOZJU9PmsR.PwFmBKuBQtr8KAEW2AawPeTqInjHb3WUbv4oPO"
]
